### ISSUE TITLE
Tap Action

### ISSUE THREAD

**Issue by milothomas** [thomasloven/lovelace-template-entity-row#10]
Can the tap action be added as a config for the card?

**Comment by Mariusthvdb** [comment]
actions would be nice, or, since this is meant to be in an entities card, have it use the regular options for entity (more-info etc etc)

**Comment by tdejneka** [comment]
+1

I currently use Custom-UI to dynamically set an entity row's icon and icon-color. I began exploring replacements for Custom-UI and managed to duplicate the desired functionality using `card-mod` (for icon color) and `template-entity-row` (for icon). However, the showstopper (for my application) is that the resulting entity row cannot be clicked to reveal the entity's `more-info` panel. 

Please consider adding this capability to a future release of `template-entity-row`.

**Comment by i00** [comment]
@thomasloven  ... any documentation coming for this?

Thanks
