### ISSUE TITLE
Feature request: show time without having to show points

### ISSUE THREAD

**Issue by andyfsimon** [thomasloven/lovelace-template-entity-row#102]
I like the graphs very much, but I don't like how it shows the points, especially when there are many per hours (like one every ten minutes). If we hide the points we lose the information about time.
Would it be possible to hide the points but keep the time information visible somehow? Either by hovering with the mouse (like for the points) or with a time scale below...

**Comment by thomasloven** [comment]
Huh?

**Comment by andyfsimon** [comment]
I'll try to explain better. With the show_points active, this is what a graph looks like:
![image](https://user-images.githubusercontent.com/15921067/217213128-a7245837-d8b4-4fd7-857c-d4d76bb74c1a.png)

What I don't like here is the way the points show up as circles and ruin the picture. On the other hand, if I disable the points (show_points = false) I lose the information about the time on the x axis.

**Comment by thomasloven** [comment]
https://github.com/kalkih/mini-graph-card

**Comment by andyfsimon** [comment]
Huh?
