### ISSUE TITLE
State is 'off' if not set after 1.3.0

### ISSUE THREAD

**Issue by bcutter** [thomasloven/lovelace-template-entity-row#106]
This was looking fine until 1.3.0:

```
type: custom:template-entity-row
name: '* TextTextText'
secondary: 'Text'
icon: none
active: false
```

giving expected

![grafik](https://user-images.githubusercontent.com/13799156/228944002-b4c43f73-5677-4426-b7eb-2d27754480a0.png)

Since 1.3.1/1.3.2 (currently running 1.3.2) the same code gives

![grafik](https://user-images.githubusercontent.com/13799156/228944081-da2171d8-c5c5-424e-9630-42b8947f2cd3.png)

To sum up: if no entity is specified and `state` is not set, state always defaults to `off` instead of showing nothing.

Workaround: Use `state: ''`

```
type: custom:template-entity-row
name: '* TextTextText'
secondary: 'Text'
state: ''
icon: none
active: false
```

**Comment by ildar170975** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/71872483/230471459-76589293-b40d-4dfa-a057-2876e5df6ac9.png)
