### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'styleSheet')

### ISSUE THREAD

**Issue by osnwt** [thomasloven/lovelace-template-entity-row#108]
Since one of past updates my dashboard stopped showing template rows.  Nothing was changed/added to the configuration.

Console shows series of the following errors:

```
caught TypeError: Cannot read properties of undefined (reading 'styleSheet')
    at template-entity-row.js:1:4391
    at Array.map (<anonymous>)
    at template-entity-row.js:1:4352
    at Et.createRenderRoot (template-entity-row.js:1:4555)
    at Et.createRenderRoot (template-entity-row.js:1:14978)
    at Et.connectedCallback (template-entity-row.js:1:4666)
    at Et.connectedCallback (template-entity-row.js:1:15564)
    at M.S (lit-html.ts:1402:53)
    at M.T (lit-html.ts:1445:36)
    at M.$ (lit-html.ts:1551:12)
```

Interesting, sometimes it still shows all, and no such errors logged. But most of the time it does not work.

Tested with MacOS Safari and MacOS Chrome - exactly the same issue.

Do you have any ideas why it can misbehave? If not, I should try to bisect versions and try to find the one caused this change. But maybe it's something already known.

All cards installed as modules:

```
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-auto-entities/auto-entities.js
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    - /hacsfiles/lovelace-template-entity-row/template-entity-row.js
```

In Safari:
![image](https://user-images.githubusercontent.com/1081613/231825025-e295e0f0-a5f4-4702-8cba-9872bbc15834.png)

**Comment by ildar170975** [comment]
Post a minimal test card where you faced the issue.

**Comment by osnwt** [comment]
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: input_number.health_charge_threshold
```

**Comment by osnwt** [comment]
I saw neither until some update. Well, it seem the only way is to try on a fresh system.

As for the correct installation way, it was taken from here: https://github.com/thomasloven/lovelace-template-entity-row

<img width="437" alt="image" src="https://user-images.githubusercontent.com/1081613/233047647-b1fd4675-1b5d-46d4-8fb2-52324a37d9c1.png">

Then from here: https://github.com/thomasloven/lovelace-card-mod#installing

![image](https://user-images.githubusercontent.com/1081613/233046927-c1c6378d-c96b-48ff-9828-b279aeb2cfd2.png)

Would be great to update the manual where it suggests to install it as a module, but below shows an example of installation as a resource.

**Comment by ildar170975** [comment]
> Then from here: https://github.com/thomasloven/lovelace-card-mod#installing

That was about card-mod.

Btw, I myself using HACS, no issues...

**Comment by thomasloven** [comment]
> As for the correct installation way, it was taken from here: https://github.com/thomasloven/lovelace-template-entity-row
> 
> <img alt="image" width="437" src="https://user-images.githubusercontent.com/1081613/233047647-b1fd4675-1b5d-46d4-8fb2-52324a37d9c1.png">

That's a different thing
https://www.home-assistant.io/dashboards/dashboards/#resources

**Comment by osnwt** [comment]
Wow, it was a bit confusing due to different configs where both refer to a "module":

```
lovelace:
  resources:
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
```

But after changing like above, everything now works!

Thanks a lot!
