### ISSUE TITLE
click on entity to see the state history

### ISSUE THREAD

**Issue by basnijholt** [thomasloven/lovelace-template-entity-row#11]
Title says it all.

For me, now I have this:
![image](https://user-images.githubusercontent.com/6897215/72689967-af539b00-3b17-11ea-847e-501255357014.png)

It would be great that if I clicked on it, I would see the window that pops up normally when clicking on an entity.

This window I mean, sorry, don't know the proper term (but then for the correct entity of course):
![image](https://user-images.githubusercontent.com/6897215/72689982-d8742b80-3b17-11ea-86ce-6054610c2b8c.png)

**Comment by MizterB** [comment]
I would recommend even more robust behavior...in addition to providing the ability to display an entity's 'more-info' popup as requested above, it would be great if the user could provide a custom card to show in that popup window as well.  Looks like the logic is built into card-tools now - can it be applied here?

**Comment by fanaticDavid** [comment]
+1 for providing a way to show the more-info popup when clicking on a template entity row, just like it would pop up when clicking on a normal entity row. Other than that, this is an improvement over secondaryinfo-entity-row 😄
