### ISSUE TITLE
Errorlog: Der Spezifizierer "@rollup/plugin-node-resolve"

### ISSUE THREAD

**Issue by ZIOOIZ8** [thomasloven/lovelace-template-entity-row#110]
I have this Error in Errorlog of Homeassistant and I can't resolve it, because I had no idea to do this:

Logger: frontend.js.latest.202304111
Source: components/system_log/__init__.py:257
First occurred: 21:16:00 (3 occurrences)
Last logged: 21:25:35

    http://192.168.150.35:8123/hacsfiles/lovelace-template-entity-row/rollup.config.js:1:24 TypeError: Der Spezifizierer "@rollup/plugin-node-resolve" war ein blanker Spezifizierer, wurde aber nicht zu etwas neu zugeordnet. Relative Modulspezifizierer müssen mit "./", "../" oder "/" beginnen.
    http://192.168.150.35:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5300 TypeError: i is null
![grafik](https://user-images.githubusercontent.com/87153886/232889944-85b8a49d-cc4e-4f5c-8351-c424b7809ca3.png)

**Comment by thomasloven** [comment]
Seems something went wrong with HACS. Try reinstalling template-entity-row.

**Comment by ZIOOIZ8** [comment]
Thanks for the info. I had installed the card manually at the time, now I deleted it and reinstalled completely via HACS. I will continue to monitor it and get back to you if the error occurs again.
