### ISSUE TITLE
How to add "secondary_info: last-changed"?

### ISSUE THREAD

**Issue by flipdream** [thomasloven/lovelace-template-entity-row#113]
Any option to add "secondary_info: last-changed" for a entity in with this card?

**Comment by ildar170975** [comment]
```
    secondary: >-
      {{relative_time(states[config.entity].last_changed)}} ago
```

**Comment by flipdream** [comment]
Perfect, thanks ildar170975

**Comment by ildar170975** [comment]
Close the issue then if solved

**Comment by bcutter** [comment]
> ```
>     secondary: >-
>       {{relative_time(states[config.entity].last_changed)}} ago
> ```

Unfortunately depending on your local language that's a bit more difficult. Here's a working example for German:

```
        secondary: >
          Vor {{ relative_time(states[config.entity].last_changed) | replace ('seconds','Sekunden') | replace ('minutes','Minuten') |
          replace ('hours','Stunden') | replace ('hour','Stunde') | replace
          ('days','Tagen') | replace ('day','Tag') | replace
          ('weeks','Wochen') }}
```

**Comment by ildar170975** [comment]
"Templates engine" is provided by HA, and German users must be happy to have at least SOME localizations, and other humans may not be so lucky:
![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/c39e27c2-3371-40dc-858d-52486f2dcab5)
