### ISSUE TITLE
Formatting Numbers

### ISSUE THREAD

**Issue by marcolino7** [thomasloven/lovelace-template-entity-row#115]
Hi,
I use this plugin to templating some numbers. I am in Italy so we use comma as decimal separator and dot as thousand separator.
![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/11460036/37ddfa37-4bfc-4c30-b86a-92b6d41fecd2)
As you can see in screenshoot, the red rounded line is templated, comma separator il wrong and thousand separator missing.
All other values that are not templated, are fine.
Here is template I use:
`{{ state_attr('sensor.consumo_caldaia', 'last_period') | float }} Wh`

Thanks in Advance
Marco

**Comment by ildar170975** [comment]
> {{ state_attr('sensor.consumo_caldaia', 'last_period') | float }} Wh

Could you test this template in Dev tools -> Template?
I observe SAME output for all defined number formats.

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/b77a9145-ab35-4574-8e88-d80ee644e7ce)

Seems this is a common issue with templates in HA.

**Comment by marcolino7** [comment]
Hi,
![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/11460036/ba5bad9d-dc5b-4956-a5dd-7727e0cd472a)
you are right. I will ask to HA community.

Thanks

**Comment by marcolino7** [comment]
Hi,
for who have my issue, here is a fancy solution:

https://community.home-assistant.io/t/decimal-and-thousand-separator-are-not-honored-in-templating/640567
