### ISSUE TITLE
Time to retire secondaryinfo-entity-row?

### ISSUE THREAD

**Issue by MizterB** [thomasloven/lovelace-template-entity-row#12]
Looks like this new custom card provides the ability to override the secondary info with the flexibility of Jinja2 templates.  Since my secondaryinfo-entity-row relies on your old 'custom' template engine in card-tools, have we finally reached a point where we should direct users to this more robust solution instead?

**Comment by noxhirsch** [comment]
That was my first thought, too - but at the moment the template-entity-row only works for sensors (and is missing more-info / tap-action) and does not work for entities with toggles or buttons.

**Comment by iantrich** [comment]
This should allow for the deprecation of it: https://github.com/home-assistant/home-assistant-polymer/pull/4704

**Comment by MizterB** [comment]
Even better.  Glad to see this capability going native!

**Comment by iantrich** [comment]
we'll see if it gets approved ;)

**Comment by Mariusthvdb** [comment]
> does not work for entities with toggles or buttons.

Yes, which is really a pity, since it does support the use of 'entity'. Did you already create a feature request for that, couldn't find it, sorry.

If not, might be a good idea to ask Thomas if he would welcome that?

**Comment by noxhirsch** [comment]
> Did you already create a feature request for that, couldn't find it, sorry.

Here's the feature request for toggle support (none for button support so far): https://github.com/thomasloven/lovelace-template-entity-row/issues/4
