### ISSUE TITLE
Status localization is not honored

### ISSUE THREAD

**Issue by chemelli74** [thomasloven/lovelace-template-entity-row#122]
Unfortunately as soon as I add this card, entity status revert to default.

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/57354320/f1290e85-5e8d-4ad3-87cb-9958321659ac)

vs

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/57354320/b8f5b8b5-277f-4e8f-b91c-68ed03534762)

**Comment by ildar170975** [comment]
The card shows a "raw" state, i.e. this is expected behaviour.
Here is a way (check readme) to localize:
```
type: entities
entities:
  - type: custom:template-entity-row
    entity: person.ildar
    state: >-
      _(component.device_tracker.entity_component._.state.{{states(config.entity)}})
  - type: custom:template-entity-row
    entity: person.ildar
```      
![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/71872483/783f8678-1065-4ff6-9e3d-c324fd834438)

**Comment by chemelli74** [comment]
Thx for the clarification.
I would expect that the default behaviour is the same as built-in entities.
And eventually specify a "`state: raw`" if a user want it.

**Comment by chemelli74** [comment]
Tested and seems it doesn't follow `device_class: gas`

![image](https://github.com/thomasloven/lovelace-template-entity-row/assets/57354320/80944d83-7bfc-4530-b48c-e0ceb1c6d780)

**Comment by ildar170975** [comment]
1. Your template is wrong. No device_class is defined. Must be `_(component.binary_sensor.entity_component.gas.state.{{states(config.entity)}})`.
2. "it doesn't follow" - these constants are provided by HA, not by this custom card.

**Comment by chemelli74** [comment]
Got it, thx a lot for your time !

**Comment by Mariusthvdb** [comment]
personally I feel this should be reopened as a config like:
```
      - type: custom:template-entity-row
        entity: device_tracker.private_ble_device_marijn
        secondary: >
          Verbonden: {{states('sensor.private_ble_device_marijn_connection')}}
```

so, without a state template, should optimally really show the localized state, and not require a dedicated template to do so.

Agree with @chemelli74 on his thoughts that default should localize. if possible.
that might constitute a FR, but given this is new functionality, Id hope this could be implemented.

also those template formats are really peculiar, and not core HA style. 

```
_(state.binary_sensor.motion.off)
```

is very uncommon. if a state of a binary template would be involved and lokalisation must be done with an underscore, shouldnt it better be configured as `{{_states('binary_sensor.motion_sensor')}}` .

that way it would still use the known jinja syntax, and only requirement would be the additional _

how could this be thought to be user friendly....
```
        state: >-
          _(component.device_tracker.entity_component._.state.{{states(config.entity)}})
```

compare with
```
      - type: custom:button-card
        entity: device_tracker.private_ble_device_marijn
        show_state: true
```

which does just that, follow core HA style and shows the translated state

hopefully[ this PR](https://github.com/home-assistant/core/pull/96906) will allow us to simply use `state_translated('device_tracker.private_ble_device_marijn')}}` or `state_translated('binary_sensor.motion')}}` soon!

**Comment by chemelli74** [comment]
hi @ildar170975, can you be so kind to tell me how to get the zone nome ?
Usual `device_tracker` behaviour is:

- home (localized)
- not_home (localized)
- zone1 name (ex. Office)
- zone2 name (ex. Gym)

Cannot achive the same with your suggestion.

**Comment by ildar170975** [comment]
@chemelli74 
I do not understand((
Please elaborate.

**Comment by chemelli74** [comment]
When a `device_tracker` entity enter a zone, the status of the tracker takes the name of the zone itself.
Instead when it's in a unknown zone is just "`Away`" and when at home is "`Home`".
Last two are localized, but the zone names not of course.

I cannot achive the result of getting the correct status with template-entity-row :-(

If I add           the code for "state:" then I get Away and Home localized, but a bad status for all known zones.
If I don't add the code for "state:" then I get all known zones right, but "`home`" and "`not_home`" raw.

**Comment by ildar170975** [comment]
> When a device_tracker entity enter a zone, the status of the tracker takes the name of the zone itself.

It takes a `friendly_name` of the zone, "Home" (localized name of `home`), "Away" (localized name of `not_home`).

> If I add the code for "state:" then I get Away and Home localized, but a bad status for all known zones.

When using t-e-r, you need to use those `_(...)` functions only to get localized `home` & `not_home`.
I.e. use a template like
```
if home or not_home
  use _(...)
else
  use states(config.entity)
```

**Comment by chemelli74** [comment]
Just for future reference if others will find this issue, here the final working code:

```jinja
    state: |-
      {%- if states(config.entity) not in ['home', 'not_home'] -%}
          {{ states(config.entity) }}
      {%- else -%}
          _(component.device_tracker.entity_component._.state.{{states(config.entity)}})
      {%- endif -%}
```

Thank you so much for your assistance and solution.

**Comment by Mariusthvdb** [comment]
ive just installed todays dev, and this is now available:

```
type: entities
entities:
  - type: custom:template-entity-row
    name: Translated state
    entity: person.marijn
    state: |
      {{state_translated(config.entity)}}
```

and working beautifully.

<img width="566" alt="Scherm­afbeelding 2024-02-16 om 12 22 08" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/a6c78013-1890-48ea-b13a-351823c2bc7b">

<img width="337" alt="Scherm­afbeelding 2024-02-16 om 12 28 04" src="https://github.com/thomasloven/lovelace-template-entity-row/assets/33354141/cf5068fc-08f4-47b1-98e9-d3f286f81e8a">

seems the latest PR on localization for template-entity-row this issue is discussing should again be reverted (taken out) because of core support for localization
Hope @thomasloven will have a look
