### ISSUE TITLE
HACS installation only on HASS v0.107.0b1+ 

### ISSUE THREAD

**Issue by milothomas** [thomasloven/lovelace-template-entity-row#19]
Does this only work with 0.107.0b1 and upwards?

![image](https://user-images.githubusercontent.com/20719501/76685702-cd330d00-663b-11ea-9809-dd3f22cf422f.png)

**Comment by thomasloven** [comment]
That's what "requires minimum version" usually means.

Version 1.0.1 works with earlier versions, though.

**Comment by milothomas** [comment]
Hey, gives the same message when selecting 1.0.1. May well be an issue with HACS...

![Screenshot_20200316-003811~2](https://user-images.githubusercontent.com/20719501/76708690-d8ab3480-671e-11ea-95cf-98787470bc1a.jpg)

**Comment by thomasloven** [comment]
Then HACS doesn't work the way I assumed it did. 

Installing [this](https://github.com/thomasloven/lovelace-template-entity-row/releases/tag/1.0.1) manually should work for you.
