### ISSUE TITLE
FR: support for templating on Unit

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#33]
Would be really nice if we could further refine the frontend using the templates in your card, by adding support for the Unit field, eg:
```
            type: custom:template-entity-row
            state: >
              {{states(config.entity)}}
            secondary: >
              {{state_attr(config.entity,'date')}}
            unit: >
              {{'Day' if state_attr(config.entity,'days') == '1' else 'Days'}}
```

thanks for considering !

**Comment by thomasloven** [comment]
What's the difference from
```yaml
state: {{ states(config.entity) }} {{'Day' if state_attr(config.entity, 'days') == '1' else 'Days'}}
```
?

**Comment by Mariusthvdb** [comment]
Not sure ;-)
Guess put like your template, we 'fake' a State and Unit into 1 line, while separating like in mine, we adhere to the HA usage of state and unit_of_measurement ?

**Comment by thomasloven** [comment]
I think this adds unnecessary complexity. The difference between value and unit doesn't matter because this is purely for display purposes.
