### ISSUE TITLE
input_number loses slider

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-template-entity-row#36]
when using a secondary line:

```
      - input_number.front_room_lux
      - type: custom:template-entity-row
        entity: input_number.front_room_lux
        secondary: >
          {{states('sensor.front_room_sensor_light_level')}} lx
```

<img width="345" alt="Schermafbeelding 2020-09-14 om 09 33 07" src="https://user-images.githubusercontent.com/33354141/93057252-e6118f00-f66d-11ea-947a-a058d9fac014.png">

or even with the code above, using only the state:
<img width="340" alt="Schermafbeelding 2020-09-14 om 09 34 05" src="https://user-images.githubusercontent.com/33354141/93057256-e7db5280-f66d-11ea-9621-1bcc5716b5b6.png">

is this a user error? would be really nice to be able to show the slider, and a secondary line
thanks for having a look

**Comment by thomasloven** [comment]
Template-entity-row only displays a value.
