### ISSUE TITLE
Feature Request: Toggle support

### ISSUE THREAD

**Issue by noxhirsch** [thomasloven/lovelace-template-entity-row#4]
Hi,
this is a great card, thank you!
It would be cool to have the option to use a toggle. Then I could use the toggle to switch an entity and use the left side to show some information about this entity.

By the way: It would be amazing to have the conditional row as "advanced conditional card"! This would get the conditional card a whole new world of options (especially to react on device ids etc).
(sorry that I added this here - didn't want to open an extra issue for something that has just barely to do with this card)

**Comment by thomasloven** [comment]
The second part is an upcoming feature of [state-switch](https://github.com/thomasloven/lovelace-state-switch).

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-state-switch/releases/tag/4

**Comment by noxhirsch** [comment]
I've already subscribed to releases for state-switch after your sneak-peek :) At this moment I'm testing the state-switch-card and loving it - thank you! :)

**Comment by Mariusthvdb** [comment]
not really sure if this is still under development, but being able to see the toggle on a switch entity would be really nice:

```
          - type: custom:template-entity-row
            entity: switch.sw_boiler_bijkeuken_sc
            active: >
              {{is_state(config.entity,'on')}}
            secondary: >
              Actueel verbruik: {{states('sensor.boiler_bijkeuken_actueel')}} watt
```

shows the state, and not the toggle:

<img width="428" alt="Schermafbeelding 2020-05-18 om 10 33 41" src="https://user-images.githubusercontent.com/33354141/82191612-0feebb00-98f3-11ea-979d-c9b3e8d3cc00.png">

forgive me if this was posted elsewhere already (think I did it myself, but couldn't find it in this repo....)

**Comment by Mariusthvdb** [comment]
polite nudge...
did you ever consider this? adding the possibility of the toggle (instead of state) if entity is a switch?

**Comment by DavidFW1960** [comment]
Yes a toggle option would be great..

**Comment by bcutter** [comment]
So where´s the toggle "feature"? Would be really awesome. I need to...
a) use the secondary_info for a specific text and
b) use the tap_action "navigate" and
c) use the switch/toggle

...in one specific use-case so currently I use 'custom:auto-entities' for this which does everything except fulfill requirement a) which is why I was looking into the 'custom:template-entity-row' - which on the other hand lacks support of c) (don´t know if b) is possible yet).

**+1 for the toggle support instead of state text (on/off) :-)**

**Comment by emufan** [comment]
Toggle support (instead of displaying state) would solve a lot of requirements here as well.

**Comment by thomasloven** [comment]
Added in 1.3.0

**Comment by Mariusthvdb** [comment]
In words too: thank you very much, makes this magical card even more versatile. Much appreciated!

**Comment by emufan** [comment]
Exactly: More than great. 

I'm thinking every day at nearly every requirement I have, how great it would be, if directly in HA and in general, every (!) lovelace/UI yaml string would accept jinja2 and every config yaml string as well. Directly. Every string. This would make live such easier and a lot of workarounds not needed anymore.

**Comment by chinyaolin** [comment]
Thank You.
wait for this function for long time.
