### ISSUE TITLE
Uncaught TypeError: i.replace is not a function

### ISSUE THREAD

**Issue by igorbumba** [thomasloven/lovelace-template-entity-row#44]
**Home Assistant Core Integration**
version: 0.118.2
installation_type: Home Assistant Container
dev: false
hassio: false
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.4.59+
arch: x86_64
timezone: Europe/Zagreb

<hr />

Logger: frontend.js.latest.202011112
Source: components/system_log/__init__.py:193
First occurred: 7:31:43 PM (12 occurrences)
Last logged: 7:31:44 PM

http://IP:8123/local/plugins/template-entity-row.js:1:2531 Uncaught TypeError: i.replace is not a function

**Comment by thomasloven** [comment]
Please make sure you are using the latest version of template-entity-row.
You can see the current version in the browser console.

**Comment by igorbumba** [comment]
![image](https://user-images.githubusercontent.com/11750417/99915926-23963680-2d07-11eb-8074-b90710c34e9f.png)

**Comment by igorbumba** [comment]
That's the latest version I downloaded from https://github.com/thomasloven/lovelace-template-entity-row/releases/tag/1.1.1

It still says version 1.1.0 in the console.

**Comment by thomasloven** [comment]
Then you need to refresh your cache. It's described in the guide linked from the readme.
