### ISSUE TITLE
Q: How do I emulate the regular entity `secondary-info: last-updated` feature?

### ISSUE THREAD

**Issue by nickdos** [thomasloven/lovelace-template-entity-row#57]
I'm migrating some entities from regular Lovelace entities to `template-entity-row`entities and I'm struggling to show the simple `secondary_info: last-changed` feature.

I thought this might work but It doesn't: `secondary: '{{ relative_time( states[config.entity].last_updated }}'`. This is for a `cover` entity and the second line is just blank using the above syntax.

Thanks in advance.

**Comment by thomasloven** [comment]
`relative_time(` needs a closing `)`.

**Comment by nickdos** [comment]
Did you read the issue description? I stated I tried `relative_time()` and it didn't work.

**Comment by thomasloven** [comment]
I did. And there's clearly a `)` missing in it.

![image](https://user-images.githubusercontent.com/1299821/123538999-c4ceea80-d737-11eb-9757-8cc6256bc42f.png)

**Comment by nickdos** [comment]
OK - I didn't understand your answer. I thought "needs a closing" was equivalent to "needs a closure" (in the coding sense) and thus you were saying insert relevant code in here.

**Comment by thomasloven** [comment]
No worries.

Did a ) help?

**Comment by nickdos** [comment]
Yes, the missing `)` was the problem. I'm too used to using an IDE it seems - I wish LoveLace editor had syntax checking and highlighting. Sorry for the confusion.
