### ISSUE TITLE
Feature Request - Light Color

### ISSUE THREAD

**Issue by tungmeister** [thomasloven/lovelace-template-entity-row#59]
Hi,
I'm wanting to use this to display the states of certain lights without the toggle showing etc. Would be great if the active colour could be defined as the value of the light it's displaying as is shown with a standard entity row.

**Comment by thomasloven** [comment]
You forgot to tell me what you tried so far
![image](https://user-images.githubusercontent.com/1299821/126004647-da6d561d-bb62-461c-affc-d72a8b9e170c.png)

**Comment by tungmeister** [comment]
@thomasloven Sorry, I'd missed the part in the documentation regarding referencing an entity for icon etc. It's working fine now, Thanks for this one! Closing
