### ISSUE TITLE
Entity is showed twice since upgrading HA to 2021.7.4

### ISSUE THREAD

**Issue by sagilo** [thomasloven/lovelace-template-entity-row#60]
I used 2021.4.x and upgraded to July release, since then, one of the cards is now showing the entity twice.
Here is the configuration for this entity:
```
  - type: custom:template-entity-row
    icon: mdi:scale
    name: Worked today
    entity: sensor.switcher_on_today
    state: '{{ (states.sensor.switcher_on_today.state | float * 60) | int }} m'
```
See the second row:
![image](https://user-images.githubusercontent.com/5019344/126865497-eaf71aae-161b-4a94-803b-6c8fbdabca77.png)

Altering the  name or icon is updating both the entities

**Comment by thomasloven** [comment]
Please copy and paste what your browser console says about template-entity-row.

**Comment by sagilo** [comment]
```
TEMPLATE-ENTITY-ROW 1.1.1 IS INSTALLED 
```

**Comment by thomasloven** [comment]
So that's an eight month old version...
