### ISSUE TITLE
Different action for Secondary info?

### ISSUE THREAD

**Issue by brandondb1** [thomasloven/lovelace-template-entity-row#63]
This is a great tool!  Thank you!

Is there a way to have a separate tap_action for the secondary info row?  I'd like to have the admin URL of devices show as secondary and be clickable.  Alternatively, if it can be shown as an HREF that would work for my use case too.

Thanks!

**Comment by thomasloven** [comment]
Not going to happen. Imagine trying to hit that on mobile.

**Comment by brandondb1** [comment]
Yeah, that's true...long press for a secondary action is much easier.  Thanks again for all the great stuff you've made!
