### ISSUE TITLE
Custom element doesn't exist: template-entity-row.

### ISSUE THREAD

**Issue by DENightOne** [thomasloven/lovelace-template-entity-row#65]
template-entity- row has been working perfectly for months, then after todays update to core-2021.9.4 it no longer works/is found.  Reinstalling does nothing to fix the problem.  I can only assume the update has a breaking change.  or is it just me?

**Comment by wel0z** [comment]
mee to 😭

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#things-suddenly-stopped-working
