### ISSUE TITLE
Localization: the "_(key)" is processed for "evaluated" templates

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-template-entity-row#83]
Also described here: https://community.home-assistant.io/t/template-entity-row-put-templates-in-an-entities-row/160167/81?u=ildar_gabdullin

Consider this example:
```
  - type: custom:template-entity-row
    entity: sun.sun
    state: >-
      {% set VALUE = states(config.entity) -%}
      {%- set LOCALIZED_VALUE = '_(component.sun.state._.'+ VALUE + ')' -%}
      {{LOCALIZED_VALUE}}
```
![изображение](https://user-images.githubusercontent.com/71872483/183081459-20adeea2-7f07-414b-84db-5a576fce2c55.png)

Now try this:
```
    state: >-
      {% set VALUE = states(config.entity) -%}
      {%- set LOCALIZED_VALUE = '_(component.sun.state._.'+ VALUE + ')' -%}
      {{LOCALIZED_VALUE | upper }}
```
![изображение](https://user-images.githubusercontent.com/71872483/183081496-edef3c4a-0cf4-436d-a190-c9231569eca2.png)

Seems that "_(key)" cannot be processed along with other templating and is mainly not supposed to be used INSIDE a template:
```
state: >-
  _(component.sun.state._.{{states(config.entity)}})
```

Not sure if t is a bug or a FR.

**Comment by thomasloven** [comment]
That's just how it works.

The template itself is processed and evaluated in the backend, i.e. on the machine running Home Assistant.
Then the result is sent to the frontend, i.e. your browser, which does the translations.

The browser doesn't have all the state information and processing tools required to evaluate the templates, and the backend doesn't know what language your browser is set to. Therefore your proposed feature cannot be implemented without ping-ponging the template back and forth repeatedly, which could grow infinitely complex.

**Comment by ildar170975** [comment]
> The template itself is processed and evaluated in the backend, i.e. on the machine running Home Assistant.
> Then the result is sent to the frontend, i.e. your browser, which does the translations.

This really explains the issue.
Thank you, Thomas.
